version: '3.8'

services:
  php-apache:
    build:
      context: ./.docker/php-apache
      dockerfile: php-apache.Dockerfile
    depends_on:
      - db
      - memcached
    env_file:
      - ./.env
    environment:
      PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
      DB_TYPE: ${DB_CONNECTION_TYPE}
      DB_HOST: "${COMPOSE_PROJECT_NAME}-mysql-1"
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      CACHE_TYPE: ${CACHE_TYPE}
      CACHE_HOST: "${COMPOSE_PROJECT_NAME}-memcached-1"
      CACHE_PORT: ${CACHE_PORT}
    volumes:
      - ./src:/var/www/html
      - ./.docker/php-apache/php-configs.ini:/usr/local/etc/php/conf.d/php-configs.ini
    ports:
      - 80:80
    links:
      - db
      - memcached
  db:
    image: mysql
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - php82_mysql_db_data:/var/lib/mysql
    command: [
      '--default_authentication_plugin=mysql_native_password',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
  memcached:
    image: memcached:latest
  composer_installation:
    image: composer
    volumes:
      - ./src:/app
    command: composer install --ignore-platform-reqs
volumes:
  php82_mysql_db_data:   # store database into a volume so we can pause the containers